Repository rhochgraf21/Constitution, pull requests merged in 2023-09, with the labels that each got.

#32 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, ready for review

#25 fixed simple majority vote from rtp vote
  constitution.tex
Labels: ready for review

#26 fixed major projects being presented to eboard by evals
  constitution.tex
Labels: approved

#21 Resolve #9 Batch Vote Chair
  constitution.tex
Labels: approved

#18 Removed Section formerly 6.C.5, Three Tiered Vote
  constitution.tex
Labels: approved

#19 Resolve #1 Add Anti-Discrimination Clause
  constitution.tex
Labels: approved

#24 Resolve #11 Quorum Definition Unnecessarily Broad
  constitution.tex
Labels: approved
