Repository rhochgraf21/Constitution, pull requests merged in 2023-11, with the labels that each got.

#124 Resolve #58 Reduce number of words
  constitution.tex
Labels: ready for review

#23 Resolve #22 Combine Honorary and Advisory Members
  constitution.tex
Labels: help wanted, ready for review

#74 Resolve #67 4.B.4 Remove Last Paragraph
  constitution.tex
Labels: in progress

#130 Resolve #71 Condense Leave of Absence
  constitution.tex
Labels: ready for review
